version: '3'
services:
  react-app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - REACT_APP_API_URL=http://localhost:3000
      - REACT_APP_USERNAME=admin
      - REACT_APP_PASSWORD=password
    volumes:
      - .:/app
      - /app/node_modules