version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql
    environment:
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_CONNECTION_LIMIT: ${DB_CONNECTION_LIMIT}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: web_scraping_app
    platform: linux/arm64
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: scraping_user
      DB_PASSWORD: scraping_password
      DB_NAME: scraping_db
      DB_CONNECTION_LIMIT: 10
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy

volumes:
  db_data: